name: Push to AWS CodeCommit

on:
  push:
    branches:
      - master

jobs:
  push-to-codecommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      - name: Add AWS CodeCommit remote
        run: |
          git remote add codecommit https://${{ secrets.AWS_CODECOMMIT_REPO_URL }}
          git push codecommit HEAD:main
