name: Build Docker Image

on:
  push:
    branches:
      - master  # Adjust as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and tag Docker image
        run: docker-compose -f docker-compose.yaml build --build-arg VERSION=1                    
  
